feat: [DevOps] Slack notification

diff --git a/.github/workflows/e2e-test.yaml b/.github/workflows/e2e-test.yaml
--- a/.github/workflows/e2e-test.yaml
+++ b/.github/workflows/e2e-test.yaml
@@ -39,9 +39,14 @@ jobs:
           mvn $MVN_ARGS
 
       - name: "Run tests"
+        id: run_tests
         run: |
           MVN_ARGS="${{ env.MVN_MULTI_THREADED_ARGS }} surefire:test -pl :spring-app -DskipTests=false"
-          mvn $MVN_ARGS "-Daicore.landscape=${{ matrix.environment }}"
+          mvn $MVN_ARGS "-Daicore.landscape=${{ matrix.environment }}" | tee mvn_output.log # tee writes to both the console and a file
+
+          awk '/Results:/, /----/' mvn_output.log > test_error.log || true # true ensures the step doesn't fail if no match is found.
+          ERROR_MSG=$(cat test_error.log | tail +4 | head -n -4 | sed ':a;N;$!ba;s/\n/\\n/g') # Slack formatting
+          echo "error_message=$ERROR_MSG" >> $GITHUB_OUTPUT
         env:
           # See "End-to-end test application instructions" on the README.md to update the secret
           AICORE_SERVICE_KEY: ${{ secrets[matrix.secret-name] }}
@@ -75,6 +80,6 @@ jobs:
           webhook-type: incoming-webhook
           payload: |
             {
-              "text": "⚠️ End-to-end tests failed! 😬 Please inspect & fix by clicking <https://github.com/SAP/ai-sdk-java/actions/runs/${{ github.run_id }}|here>"
+              "text": "⚠️ End-to-end tests failed! 😬 Please inspect & fix by clicking <https://github.com/SAP/ai-sdk-java/actions/runs/${{ github.run_id }}|here>\n\n*Test Errors:*\n${{ steps.run_tests.outputs.error_message }}"
             }
 
