debug e2e tests

diff --git a/.github/workflows/e2e-test.yaml b/.github/workflows/e2e-test.yaml
--- a/.github/workflows/e2e-test.yaml
+++ b/.github/workflows/e2e-test.yaml
@@ -52,10 +52,13 @@ jobs:
           MVN_ARGS="${{ env.MVN_MULTI_THREADED_ARGS }} surefire:test -pl :spring-app -DskipTests=false"
           mvn $MVN_ARGS "-Daicore.landscape=${{ matrix.environment }}" 2>&1 | tee mvn_output.log # tee writes to both the console and a file
 
-          awk '/Results:/, /----/' mvn_output.log > test_error.log || true # true ensures the step doesn't fail if no match is found.
-          ERROR_MSG=$(cat test_error.log | tail +4 | head -n -4 | awk 'BEGIN{RS=""} {gsub(/"/, "\\\""); gsub(/Expecting KeySet:.*but could not find the following element\(s\):/, "Missing element: "); printf "%s\n", $0}')
+          ERROR_MSG=$(grep -E '^\[ERROR\] +[A-Za-z][A-Za-z0-9_]*\.[a-zA-Z][a-zA-Z0-9_]*:[0-9]+' mvn_output.log || true)
           echo "$ERROR_MSG"
-          echo "error_message=$ERROR_MSG" >> $GITHUB_OUTPUT
+          {
+            echo "error_message<<EOF"
+            echo "$ERROR_MSG"
+            echo "EOF"
+          } >> $GITHUB_OUTPUT
 
           if grep -q "BUILD FAILURE" mvn_output.log; then
             echo "Maven build failed."
