improve workflow

diff --git a/.github/workflows/spec-update.yaml b/.github/workflows/spec-update.yaml
--- a/.github/workflows/spec-update.yaml
+++ b/.github/workflows/spec-update.yaml
@@ -294,6 +294,12 @@ jobs:
           echo "Client generation failed. Please check the Generate step logs for details."
           exit 1
 
+      - name: "Fail if no spec changes and previous run failed"
+        if: steps.spec_diff.outputs.prev_run_success == 'false'
+        run: |
+          echo "Previous run failed and there were no spec changes since, thus failing this run as well."
+          exit 1
+
       - name: "Slack Notification"
         if: failure() && github.event.inputs.create-pr == 'true'
         uses: slackapi/slack-github-action@v2.1.1
